name: Assistance Request
description: Ask a question or seek help with this resource.
labels: ["question"]
assignees: RockinChaos
body:
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      description: The operating system you are running the app on.
      options:
        - Windows
        - Linux (X11)
        - Linux (Wayland)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Android (arm64-v8a)
        - Android (armeabi-v7a)
        - Android (x86)
        - Android (universal)
    validations:
      required: true

  - type: input
    attributes:
      label: App Version
      description: The version you're currently using (e.g., v6.0.0). Find this at the bottom of the settings menu, or on Android under Settings > App tab. Please provide the full version number, not "latest".
      placeholder: v6.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: What Do You Need Help With?
      description: A clear and concise description of your question or issue.
      placeholder: I'm trying to understand how to configure the notification settings. I want notifications to only show for certain categories, but I can't find where to set this up...
    validations:
      required: true

  - type: textarea
    attributes:
      label: What Have You Tried?
      description: List any troubleshooting steps or solutions you've already attempted.
      placeholder: I've checked the settings menu and looked through the notification options, but I couldn't find a way to filter by category...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context or screenshots (highly recommended) about this request.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Let's make sure this report is valid.
      options:
        - label: I am using the [latest stable](https://github.com/RockinChaos/Shiru/releases/latest) version of the app.
          required: true
        - label: I have searched the [frequently asked questions](https://github.com/RockinChaos/Shiru/wiki/faq) and did not find an answer.
          required: true
        - label: I have searched the [issue tracker](https://github.com/RockinChaos/Shiru/issues) and confirmed this question hasn't been asked before.
          required: true
        - label: I ticked all of these boxes without actually reading them.
          required: false
        - label: I confirm that my question is **legal and lawful**, and does not promote or link to piracy or copyrighted material.
          required: true
        - label: I acknowledge this is not a bug report and is instead a help request.
          required: true